version: "3.8"
services:
  todo_backend:
    image: node
    working_dir: /backend
    volumes:
      - .:/backend
    # command: >
    depends_on:
      - todo_db
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
  todo_db:
    image: postgres:15.3
    ports: 
      - "5432:5432"
    volumes:
      - todo_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
volumes:
  todo_db_volume:
